# Test the functionality for crawling stocks

In [1]:
import stock_lib as sl
from datetime import date

## Crawl

In [2]:
df_stock = sl.crawl_stock("NVDA", date(2026,6,1), date(2026,7,1))
df_stock.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits,percent_change
Date,,,,,,,,
2026-06-01 00:00:00-04:00,215.478858,224.608217,215.448894,224.098816,212850700,0.00,0.0,NaN
2026-06-02 00:00:00-04:00,226.915518,232.009586,221.092318,222.560608,193362900,0.00,0.0,-0.006864
2026-06-03 00:00:00-04:00,221.461887,222.560613,214.260274,214.500000,160907000,0.00,0.0,-0.036218
2026-06-04 00:00:00-04:00,213.910004,221.600006,210.970001,218.660004,169022200,0.25,0.0,0.019394
2026-06-05 00:00:00-04:00,214.529999,214.869995,204.330002,205.100006,219655500,0.00,0.0,-0.062014

In [3]:
comp = sl.crawl_company("NVDA")

## Insert into database

In [4]:
sl.upsert_company(comp)

{'status': 'Success', 'rows': 1}

In [5]:
sl.upsert_stock("NVDA", df_stock)

{'status': 'Success', 'rows': 21}

## Select functions

In [8]:
sl.get_company("NVDA")

[{'symbol': 'NVDA',
  'name': 'NVIDIA',
  'sector': 'Technology',
  'industry': 'Semiconductors',
  'description': None,
  'updated_at': '2026-08-01 13:15:49'}]

In [2]:
df_stock_db = sl.get_stock("NVDA", date(2026, 6, 1), date(2026, 7, 1))
df_stock_db.head()

,symbol,date,open,close,high,low,volume,dividends,stock_split
0,NVDA,2026-06-01,215.478858,224.098816,224.608217,215.448894,212850700,0.00,0.0
1,NVDA,2026-06-02,226.915518,222.560608,232.009586,221.092318,193362900,0.00,0.0
2,NVDA,2026-06-03,221.461887,214.500000,222.560613,214.260274,160907000,0.00,0.0
3,NVDA,2026-06-04,213.910004,218.660004,221.600006,210.970001,169022200,0.25,0.0
4,NVDA,2026-06-05,214.529999,205.100006,214.869995,204.330002,219655500,0.00,0.0

## Statistics

In [8]:
z= sl.adaptive_sig(date(2026, 6, 1), date(2026, 7, 1), 5)
df_sig = sl.spot_significant_dates(df_stock_db, "close", mean=True, sig=z, limit=10, increase=None)
df_sig

,symbol,date,open,close,high,low,volume,dividends,stock_split,percent_change,percent_increase
4,NVDA,2026-06-05,214.529999,205.100006,214.869995,204.330002,219655500,0.0,0.0,0.062014,False
10,NVDA,2026-06-15,208.919998,212.449997,212.710007,208.339996,149936700,0.0,0.0,0.035382,True

In [10]:
df_sig_1 = sl.spot_significant_dates(df_stock_db, "close", mean=True, sig=1, limit=10, increase = None)
df_sig_1

,symbol,date,open,close,high,low,volume,dividends,stock_split,percent_change,percent_increase
4,NVDA,2026-06-05,214.529999,205.100006,214.869995,204.330002,219655500,0.0,0.0,0.062014,False
15,NVDA,2026-06-23,202.169998,200.039993,203.770004,200.000000,153496200,0.0,0.0,0.041265,False
7,NVDA,2026-06-10,204.429993,200.419998,207.220001,199.919998,161746600,0.0,0.0,0.037322,False
2,NVDA,2026-06-03,221.461887,214.500000,222.560613,214.260274,160907000,0.0,0.0,0.036218,False
10,NVDA,2026-06-15,208.919998,212.449997,212.710007,208.339996,149936700,0.0,0.0,0.035382,True
13,NVDA,2026-06-18,207.330002,210.690002,211.389999,206.500000,241272000,0.0,0.0,0.029514,True
20,NVDA,2026-06-30,197.240005,200.089996,200.630005,195.110001,166476700,0.0,0.0,0.026260,True
8,NVDA,2026-06-11,201.490005,204.869995,205.660004,199.539993,158643200,0.0,0.0,0.022203,True