# Test the functionality for crawling stocks

In [1]:
import stock_lib as sl
from datetime import date

## Crawl

In [31]:
df_stock = sl.crawl_stock("NVDA", date(2026,8,1), date(2026,8,24))
df_stock.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2026-08-03 00:00:00-04:00,197.690002,208.740005,196.850006,206.639999,128406900,0.0,0.0
2026-08-04 00:00:00-04:00,211.300003,213.059998,209.050003,211.940002,134922000,0.0,0.0
2026-08-05 00:00:00-04:00,216.860001,222.220001,216.399994,219.220001,158187400,0.0,0.0
2026-08-06 00:00:00-04:00,221.529999,223.630005,217.000000,218.990005,113940600,0.0,0.0
2026-08-07 00:00:00-04:00,221.539993,224.759995,220.660004,223.960007,105669400,0.0,0.0

In [32]:
df_stock

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2026-08-03 00:00:00-04:00,197.690002,208.740005,196.850006,206.639999,128406900,0.0,0.0
2026-08-04 00:00:00-04:00,211.300003,213.059998,209.050003,211.940002,134922000,0.0,0.0
2026-08-05 00:00:00-04:00,216.860001,222.220001,216.399994,219.220001,158187400,0.0,0.0
2026-08-06 00:00:00-04:00,221.529999,223.630005,217.000000,218.990005,113940600,0.0,0.0
2026-08-07 00:00:00-04:00,221.539993,224.759995,220.660004,223.960007,105669400,0.0,0.0
2026-08-10 00:00:00-04:00,223.399994,224.139999,216.770004,217.550003,115846600,0.0,0.0
2026-08-11 00:00:00-04:00,222.169998,222.199997,216.199997,217.500000,101273100,0.0,0.0
2026-08-12 00:00:00-04:00,221.039993,225.100006,220.199997,224.089996,108783600,0.0,0.0
2026-08-13 00:00:00-04:00,225.059998,227.229996,223.710007,225.300003,98867200,0.0,0.0
2026-08-14 00:00:00-04:00,226.770004,227.490005,224.500000,225.160004,75680900,0.0,0.0
2026-08-17 00:00:00-04:00,225.979996,227.919998,224.860001,225.009995,93678700,0.0,0.0
2026-08-18 00:00:00-04:00,220.449997,221.639999,218.690002,219.740005,103128200,0.0,0.0
2026-08-19 00:00:00-04:00,221.669998,222.869995,216.759995,217.559998,96797300,0.0,0.0
2026-08-20 00:00:00-04:00,218.360001,219.860001,215.660004,216.850006,92457000,0.0,0.0
2026-08-21 00:00:00-04:00,218.419998,218.740005,214.500000,214.720001,98545600,0.0,0.0

In [5]:
comp = sl.crawl_company("MSFT")

In [6]:
comp

{'address1': 'One Microsoft Way',
 'city': 'Redmond',
 'state': 'WA',
 'zip': '98052-6399',
 'country': 'United States',
 'phone': '425 882 8080',
 'website': 'https://www.microsoft.com',
 'industry': 'Software - Infrastructure',
 'industryKey': 'software-infrastructure',
 'industryDisp': 'Software - Infrastructure',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': "Microsoft Corporation, a technology company, develops and supports a portfolio of technology solutions for individuals and businesses worldwide. Its products include operating systems, server applications, business solution applications, software development tools, desktop and server management tools, and video games; and devices, such as PCs, tablets, gaming and entertainment consoles, other intelligent devices, and related accessories. The company's Productivity and Business Processes segment offers Microsoft 365 Commercial, Enterprise Mobility + Security, Power BI, Exchange, SharePoint, Microsoft Teams, Microsoft 365 Security and Compliance, Microsoft 365 Copilot, and Windows Commercial on-premises and Office licensed on-premises. This segment also provides Microsoft 365 Consumer products and cloud services; LinkedIn, including talent solutions, marketing solutions, subscriptions, and sales solutions; Dynamics 365, a set of cloud-based applications; and on-premises ERP and CRM applications. Its Intelligent Cloud segment offers server products and cloud services; cloud and AI consumption-based services, GitHub cloud services, health and life sciences cloud services, as well as virtual desktop offerings, and other cloud services; SQL Server, Windows Server, Visual Studio, System Center, and related client access licenses; and enterprise support services, industry solutions, Microsoft partner network, and learning experience. The company's More Personal Computing segment provides Windows OEM licensing and devices comprising Surface and PC accessories; XBOX hardware, and XBOX first- and third-party content and services; XBOX Game Pass and other subscriptions; XBOX Cloud Gaming, advertising, and other cloud services; and search advertising consisting of Bing, Copilot, Microsoft News, Microsoft Edge, and third-party affiliates. It sells its products through partners and retail networks. The company was founded in 1975 and is headquartered in Redmond, Washington.",
 'fullTimeEmployees': 223000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Satya  Nadella',
   'age': 58,
   'title': 'Chairman & CEO',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 12251294,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Bradford L. Smith LCA',
   'age': 66,
   'title': 'President & Vice Chairman',
   'yearBorn': 1959,
   'fiscalYear': 2025,
   'totalPay': 4532750,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Amy E. Hood',
   'age': 53,
   'title': 'Executive VP & CFO',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'totalPay': 4444191,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Takeshi  Numoto',
   'age': 54,
   'title': 'Executive VP & Chief Marketing Officer',
   'yearBorn': 1971,
   'fiscalYear': 2025,
   'totalPay': 2871250,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Judson B. Althoff',
   'age': 52,
   'title': 'Executive VP & CEO of Commercial Business',
   'yearBorn': 1973,
   'fiscalYear': 2025,
   'totalPay': 4490115,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Carolina  Dybeck Happe',
   'age': 53,
   'title': 'Executive VP & COO',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Alice L. Jolla',
   'age': 59,
   'title': 'Corporate VP & Chief Accounting Officer',
   'yearBorn': 1966,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Matthew  Kerner',
   'title': 'CTO & Corporate VP of Worldwide Sales and Solutions',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Jonathan  Neilson',
   'title': 'Vice President of Investor Relations',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Jonathan M. Palmer',
   'title': 'Corporate Vice President & Chief Legal Officer',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 9,
 'boardRisk': 7,
 'compensationRisk': 5,
 'shareHolderRightsRisk': 2,
 'overallRisk': 5,
 'governanceEpochDate': 1785542400,
 'compensationAsOfEpochDate': 1767139200,
 'irWebsite': 'http://www.microsoft.com/investor/default.aspx',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 495.4,
 'open': 490.2175,
 'dayLow': 478.41,
 'dayHigh': 492.66,
 'regularMarketPreviousClose': 495.4,
 'regularMarketOpen': 490.2175,
 'regularMarketDayLow': 478.41,
 'regularMarketDayHigh': 492.66,
 'dividendRate': 3.64,
 'dividendYield': 0.73,
 'exDividendDate': 1787184000,
 'payoutRatio': 0.1983,
 'fiveYearAvgDividendYield': 0.79,
 'beta': 1.099,
 'trailingPE': 27.622198,
 'forwardPE': 20.376884,
 'volume': 28250867,
 'regularMarketVolume': 28250867,
 'averageVolume': 40399404,
 'averageVolume10days': 33839580,
 'averageDailyVolume10Day': 33839580,
 'bid': 478.52,
 'ask': 484.5,
 'bidSize': 3,
 'askSize': 1,
 'marketCap': 3566861025280,
 'nonDilutedMarketCap': 3678615236241,
 'fiftyTwoWeekLow': 349.2,
 'fiftyTwoWeekHigh': 553.72,
 'allTimeHigh': 555.45,
 'allTimeLow': 0.088542,
 'priceToSalesTrailing12Months': 10.74877,
 'fiftyDayAverage': 412.7756,
 'twoHundredDayAverage': 432.4805,
 'trailingAnnualDividendRate': 3.64,
 'trailingAnnualDividendYield': 0.007347598,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 3618830811136,
 'profitMargins': 0.40305,
 'floatShares': 7414481428,
 'sharesOutstanding': 7425545491,
 'sharesShort': 81311791,
 'sharesShortPriorMonth': 89063316,
 'sharesShortPreviousMonthDate': 1782777600,
 'dateShortInterest': 1785456000,
 'sharesPercentSharesOut': 0.011,
 'heldPercentInsiders': 0.00090000004,
 'heldPercentInstitutions': 0.7593,
 'shortRatio': 2.17,
 'shortPercentOfFloat': 0.011,
 'impliedSharesOutstanding': 7425545491,
 'bookValue': 59.565,
 'priceToBook': 8.0643,
 'lastFiscalYearEnd': 1782777600,
 'nextFiscalYearEnd': 1814313600,
 'mostRecentQuarter': 1782777600,
 'earningsQuarterlyGrowth': 0.313,
 'netIncomeToCommon': 133748998144,
 'trailingEps': 17.39,
 'forwardEps': 23.57328,
 'pegRatio': 1.61,
 'lastSplitFactor': '2:1',
 'lastSplitDate': 1045526400,
 'enterpriseToRevenue': 10.905,
 'enterpriseToEbitda': 18.631,
 '52WeekChange': -0.04196483,
 'SandP52WeekChange': 0.21436763,
 'lastDividendValue': 0.91,
 'lastDividendDate': 1779321600,
 'quoteType': 'EQUITY',
 'currentPrice': 480.35,
 'targetHighPrice': 870.0,
 'targetLowPrice': 400.0,
 'targetMeanPrice': 569.5583,
 'targetMedianPrice': 550.0,
 'recommendationMean': 1.35714,
 'recommendationKey': 'strong_buy',
 'numberOfAnalystOpinions': 53,
 'totalCash': 76842999808,
 'totalCashPerShare': 10.348,
 'ebitda': 194237005824,
 'totalDebt': 128812998656,
 'quickRatio': 1.099,
 'currentRatio': 1.23,
 'totalRevenue': 331839012864,
 'debtToEquity': 29.118,
 'revenuePerShare': 44.668,
 'returnOnAssets': 0.14088,
 'returnOnEquity': 0.34039003,
 'grossProfits': 225465008128,
 'freeCashflow': 16545500160,
 'operatingCashflow': 182934994944,
 'earningsGrowth': 0.317,
 'revenueGrowth': 0.177,
 'grossMargins': 0.67944,
 'ebitdaMargins': 0.58534,
 'operatingMargins': 0.45111,
 'financialCurrency': 'USD',
 'symbol': 'MSFT',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Nasdaq Real Time Price',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'longName': 'Microsoft Corporation',
 'corporateActions': [{'header': 'Dividend',
   'message': 'MSFT announced a cash dividend of $0.91 with an ex-date of Aug. 20, 2026',
   'meta': {'eventType': 'DIVIDEND',
    'dateEpochMs': 1787198400000,
    'amount': '0.91'}}],
 'postMarketTime': 1787011196,
 'regularMarketTime': 1786996801,
 'exchange': 'NMS',
 'messageBoardId': 'finmb_21835',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'gmtOffSetMilliseconds': -14400000,
 'market': 'us_market',
 'esgPopulated': False,
 'shortName': 'Microsoft Corporation',
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 511108200000,
 'postMarketChangePercent': -0.07990415,
 'postMarketPrice': 479.9662,
 'postMarketChange': -0.38381958,
 'regularMarketChange': -15.05,
 'fulldayPrice': 479.9662,
 'regularMarketDayRange': '478.41 - 492.66',
 'fullExchangeName': 'NasdaqGS',
 'averageDailyVolume3Month': 40399404,
 'fiftyTwoWeekLowChange': 131.15,
 'fiftyTwoWeekLowChangePercent': 0.3755727,
 'fiftyTwoWeekRange': '349.2 - 553.72',
 'fiftyTwoWeekHighChange': -73.369965,
 'fiftyTwoWeekHighChangePercent': -0.13250373,
 'fiftyTwoWeekChangePercent': -4.1964827,
 'dividendDate': 1788998400,
 'earningsTimestamp': 1785355200,
 'earningsTimestampStart': 1793217600,
 'earningsTimestampEnd': 1793217600,
 'earningsCallTimestampStart': 1785360600,
 'earningsCallTimestampEnd': 1785360600,
 'isEarningsDateEstimate': True,
 'epsTrailingTwelveMonths': 17.39,
 'epsForward': 23.57328,
 'epsCurrentYear': 19.7106,
 'priceEpsCurrentYear': 24.370136,
 'fiftyDayAverageChange': 67.5744,
 'fiftyDayAverageChangePercent': 0.16370736,
 'twoHundredDayAverageChange': 47.869507,
 'twoHundredDayAverageChangePercent': 0.11068593,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'averageAnalystRating': '1.4 - Strong Buy',
 'cryptoTradeable': False,
 'regularMarketChangePercent': -3.03795,
 'regularMarketPrice': 480.35,
 'marketState': 'PREPRE',
 'displayName': 'Microsoft',
 'trailingPegRatio': 1.6088}

## Insert into database

In [34]:
sl.upsert_company(comp)

NameError: name 'comp' is not defined

In [35]:
sl.upsert_stock("NVDA", df_stock)

{'status': 'Success', 'rows': 15}

## Select functions

In [9]:
sl.get_company("MSFT")

[{'symbol': 'MSFT',
  'name': 'Microsoft',
  'sector': 'Technology',
  'industry': 'Software - Infrastructure',
  'description': "Microsoft Corporation, a technology company, develops and supports a portfolio of technology solutions for individuals and businesses worldwide. Its products include operating systems, server applications, business solution applications, software development tools, desktop and server management tools, and video games; and devices, such as PCs, tablets, gaming and entertainment consoles, other intelligent devices, and related accessories. The company's Productivity and Business Processes segment offers Microsoft 365 Commercial, Enterprise Mobility + Security, Power BI, Exchange, SharePoint, Microsoft Teams, Microsoft 365 Security and Compliance, Microsoft 365 Copilot, and Windows Commercial on-premises and Office licensed on-premises. This segment also provides Microsoft 365 Consumer products and cloud services; LinkedIn, including talent solutions, marketing solutions, subscriptions, and sales solutions; Dynamics 365, a set of cloud-based applications; and on-premises ERP and CRM applications. Its Intelligent Cloud segment offers server products and cloud services; cloud and AI consumption-based services, GitHub cloud services, health and life sciences cloud services, as well as virtual desktop offerings, and other cloud services; SQL Server, Windows Server, Visual Studio, System Center, and related client access licenses; and enterprise support services, industry solutions, Microsoft partner network, and learning experience. The company's More Personal Computing segment provides Windows OEM licensing and devices comprising Surface and PC accessories; XBOX hardware, and XBOX first- and third-party content and services; XBOX Game Pass and other subscriptions; XBOX Cloud Gaming, advertising, and other cloud services; and search advertising consisting of Bing, Copilot, Microsoft News, Microsoft Edge, and third-party affiliates. It sells its products through partners and retail networks. The company was founded in 1975 and is headquartered in Redmond, Washington.",
  'updated_at': '2026-08-18 05:06:01'}]

In [36]:
df_stock_db = sl.get_stock("NVDA", date(2026, 8, 17), date(2026, 8, 24))
df_stock_db

,symbol,date,open,close,high,low,volume,dividends,stock_split,percent_change_close
0,NVDA,2026-08-17,225.979996,225.009995,227.919998,224.860001,93678700,0.0,0.0,NaN
1,NVDA,2026-08-18,220.449997,219.740005,221.639999,218.690002,103128200,0.0,0.0,-0.023421
2,NVDA,2026-08-19,221.669998,217.559998,222.869995,216.759995,96797300,0.0,0.0,-0.009921
3,NVDA,2026-08-20,218.360001,216.850006,219.860001,215.660004,92457000,0.0,0.0,-0.003263
4,NVDA,2026-08-21,218.419998,214.720001,218.740005,214.500000,98545600,0.0,0.0,-0.009822

In [ ]:
df_desc = df_stock_db.describe()
sig = sl.adaptive_sig(date(2026, 8, 1), date(2026, 8, 10))
column = "close"
std_dev = df_desc.loc["std", "percent_change_"+column]
center = df_desc.loc["mean", "percent_change_"+column]
lower_range = center - (sig*std_dev)
upper_range = center + (sig*std_dev)

In [28]:
print(f"low: {lower_range}")
print(f"upper: {upper_range}")

low: -0.018784517289865826
upper: 0.03999354775121051

In [27]:
df_stock_db[
    (df_stock_db["percent_change_"+column] < lower_range) | 
    (df_stock_db["percent_change_"+column] > upper_range)
]

,symbol,date,open,close,high,low,volume,dividends,stock_split,percent_change_close,percent_increase_close
5,NVDA,2026-08-10,223.399994,217.550003,224.139999,216.770004,115846600,0.0,0.0,-0.028621,False

## Statistics

In [37]:
z= sl.adaptive_sig(date(2026, 8, 17), date(2026, 8, 24))
df_sig = sl.spot_significant_dates(df_stock_db, "close", mean=True, sig=z, limit=10, increase=None)
df_sig

,symbol,date,open,close,high,low,volume,dividends,stock_split,percent_change_close,percent_increase_close
1,NVDA,2026-08-18,220.449997,219.740005,221.639999,218.690002,103128200,0.0,0.0,0.023421,False

In [10]:
df_sig_1 = sl.spot_significant_dates(df_stock_db, "close", mean=True, sig=1, limit=10, increase = None)
df_sig_1

,symbol,date,open,close,high,low,volume,dividends,stock_split,percent_change,percent_increase
4,NVDA,2026-06-05,214.529999,205.100006,214.869995,204.330002,219655500,0.0,0.0,0.062014,False
15,NVDA,2026-06-23,202.169998,200.039993,203.770004,200.000000,153496200,0.0,0.0,0.041265,False
7,NVDA,2026-06-10,204.429993,200.419998,207.220001,199.919998,161746600,0.0,0.0,0.037322,False
2,NVDA,2026-06-03,221.461887,214.500000,222.560613,214.260274,160907000,0.0,0.0,0.036218,False
10,NVDA,2026-06-15,208.919998,212.449997,212.710007,208.339996,149936700,0.0,0.0,0.035382,True
13,NVDA,2026-06-18,207.330002,210.690002,211.389999,206.500000,241272000,0.0,0.0,0.029514,True
20,NVDA,2026-06-30,197.240005,200.089996,200.630005,195.110001,166476700,0.0,0.0,0.026260,True
8,NVDA,2026-06-11,201.490005,204.869995,205.660004,199.539993,158643200,0.0,0.0,0.022203,True